### ISSUE TITLE
pip3 install http_parser compile issue

### ISSUE THREAD

**Issue by SailM23** [DMTF/Redfish-Event-Listener#6]
c:\Users\Admin\AppData\Local\Programs\Python\Python37-32\Scripts>pip3 install http_parser
Collecting http_parser
  Using cached https://files.pythonhosted.org/packages/07/c4/22e3c76c2313c26dd5f84f1205b916ff38ea951aab0c4544b6e2f5920d64/http-parser-0.8.3.tar.gz
Installing collected packages: http-parser
  Running setup.py install for http-parser ... error
    Complete output from command c:\users\admin\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-72tekw08\\http-parser\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Admin\AppData\Local\Temp\pip-record-p2v4v4xy\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\http_parser
    copying http_parser\http.py -> build\lib.win32-3.7\http_parser
    copying http_parser\pyparser.py -> build\lib.win32-3.7\http_parser
    copying http_parser\reader.py -> build\lib.win32-3.7\http_parser
    copying http_parser\util.py -> build\lib.win32-3.7\http_parser
    copying http_parser\_socketio.py -> build\lib.win32-3.7\http_parser
    copying http_parser\__init__.py -> build\lib.win32-3.7\http_parser
    running build_ext
    building 'http_parser.parser' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\http_parser
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iparser -Ic:\users\admin\appdata\local\programs\python\python37-32\include -Ic:\users\admin\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tchttp_parser\http_parser.c /Fobuild\temp.win32-3.7\Release\http_parser\http_parser.obj
    http_parser.c
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Iparser -Ic:\users\admin\appdata\local\programs\python\python37-32\include -Ic:\users\admin\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /Tchttp_parser\parser.c /Fobuild\temp.win32-3.7\Release\http_parser\parser.obj
    parser.c
    http_parser\parser.c(6249): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6250): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6251): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6252): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6253): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(6254): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7460): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7461): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7462): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7474): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7475): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7476): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7477): error C2039: 'exc_type': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7478): error C2039: 'exc_value': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    http_parser\parser.c(7479): error C2039: 'exc_traceback': is not a member of '_ts'
    c:\users\admin\appdata\local\programs\python\python37-32\include\pystate.h(212): note: see declaration of '_ts'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "c:\users\admin\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-install-72tekw08\\http-parser\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Admin\AppData\Local\Temp\pip-record-p2v4v4xy\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Admin\AppData\Local\Temp\pip-install-72tekw08\http-parser\

c:\Users\Admin\AppData\Local\Programs\Python\Python37-32\Scripts>

**Comment by billdodd** [comment]
Looks like the released http_parser (0.8.3) is not compatible with Python 3.7: https://github.com/benoitc/http-parser/issues/76

The above-referenced issue supposedly fixes the problem, but that code hasn't been pushed out to PyPI. (In fact, the http_parser on PyPI hasn't been updated since 2013.) 

You could try (1) using Python 3.6 or (2) installing the latest http_parser from github.

**Comment by SailM23** [comment]
worked with python 3.6. thank you
